name: Tests

on:
  push:
    branches:
      - master
      - action
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        job: [linux-node-latest, linux-node-lts, mac]
        include:
          - job: linux-node-latest
            os: ubuntu-latest
            node: 13.x
            browsers: chrome, chrome-headless, firefox, firefox-headless

          - job: linux-node-lts
            os: ubuntu-latest
            node: 12.x
            browsers: chrome-headless

          - job: mac
            os: macos-latest
            node: 13.x
            browsers: safari

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Node.js (${{ matrix.node }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM install
      run: npm install

    - name: Fix ChromeDriver version
      run: |
        npm uninstall chromedriver
        npm install chromedriver@^78

    - name: Build
      run: npm run build

    - name: Enable Safari automation
      if: contains(matrix.browsers, 'safari')
      run: sudo safaridriver --enable

    - name: Test (${{ matrix.browsers }})
      env:
        TACHOMETER_E2E_TEST_BROWSERS: ${{ matrix.browsers }}
        TACHOMETER_E2E_TEST_SHOW_OUTPUT: true
      run: npm test
